---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: azure
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:

  - name: test-azure-centos7-jenkins-master
    platform: centos7
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - rhel_family
      - jenkins_master

  - name: test-azure-Windows2016-jenkins-slave
    platform: windows2016core
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - windows
      - jenkins_slaves

  - name: test-azure-Windows2019-jenkins-slave
    platform: windows2019core
    vm_size: Standard_D2s_v3
    az_location: northeurope
    az_resource_group_name: epm-ldi
    az_virtual_network_name: epm-ldi-northeurope-vnet
    az_subnet_name: epm-ldi-northeurope-subnet
    az_network_security_group: epm-ldi-northeurope-sg
    groups:
      - windows
      - jenkins_slaves
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      rhel_family:
        transport: repositories
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
        java_distribution: oracle_java
        transport: local
        java_tarball_install: false
        transport_local: /tmp/jdk-8u202-windows-x64.exe
  playbooks:
    create: ../resources/provisioning/AZURE/create.yml
    prepare: prepare.yml
    destroy: ../resources/provisioning/AZURE/destroy.yml
    verify: ../resources/tests/verify.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-azure-direct-win
verifier:
  name: ansible
  lint:
    name: ansible-lint
